name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Set Date based var for use in tag
      id: vars
      run: echo "tag=$(date +%s)" >> "$GITHUB_OUTPUT"
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/iamangus/term:latest
    - name: Push the latest Docker image
      run: docker push ghcr.io/iamangus/term:latest
    - name: retag and push
      run: docker tag ghcr.io/iamangus/term:latest ghcr.io/iamangus/term:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push ghcr.io/iamangus/term:${{steps.vars.outputs.tag}}
